In [3]:
from sklearn.datasets import load_iris

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X,y = load_iris(return_X_y=True)

In [7]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=20)

In [32]:
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

### Here all the values are continuous values so we are using Gaussian Naive Bayes

In [10]:
from sklearn.naive_bayes import GaussianNB

In [11]:
gnb = GaussianNB()

In [12]:
gnb.fit(X_train,y_train)

GaussianNB()

In [14]:
y_pred = gnb.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [16]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[12  0  0]
 [ 0 14  0]
 [ 0  3  9]]
0.9210526315789473
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.82      1.00      0.90        14
           2       1.00      0.75      0.86        12

    accuracy                           0.92        38
   macro avg       0.94      0.92      0.92        38
weighted avg       0.93      0.92      0.92        38



## TIPS Dataset

In [17]:
import seaborn as sns

In [19]:
df = sns.load_dataset('tips')

In [20]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [25]:
df['sex'].value_counts()

Male      157
Female     87
Name: sex, dtype: int64

In [26]:
df['smoker'].value_counts()

No     151
Yes     93
Name: smoker, dtype: int64

In [27]:
df['time'].value_counts()

Dinner    176
Lunch      68
Name: time, dtype: int64

In [28]:
df['day'].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [29]:
# performimg encoding for categorical columns

from sklearn.preprocessing import LabelEncoder

In [61]:
# Segregating independent and dependent features

X = df[['tip', 'sex', 'smoker', 'day', 'time', 'total_bill']] # 2D array for X 
y = df['size'] # 1D array for y

In [62]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25, random_state=42)

In [63]:
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [64]:
#label encodig for training data
# using fit transform for training data
X_train['sex'] = le1.fit_transform(X_train['sex'])
X_train['smoker'] = le2.fit_transform(X_train['smoker'])
X_train['time'] = le3.fit_transform(X_train['time'])

In [65]:
X_train.head()

tip  sex  smoker  day  time  total_bill
115  3.50    0       0  Sun     0       17.31
181  5.65    1       1  Sun     0       23.33
225  2.50    0       1  Fri     1       16.27
68   2.01    1       0  Sat     0       20.23
104  4.08    0       0  Sat     0       20.92

In [66]:
#label encodig for testing data
# using transform for testing data
X_test['sex'] = le1.transform(X_test['sex'])
X_test['smoker'] = le2.transform(X_test['smoker'])
X_test['time'] = le3.transform(X_test['time'])

In [67]:
X_test.head()

tip  sex  smoker   day  time  total_bill
24   3.18    1       0   Sat     0       19.82
6    2.00    1       0   Sun     0        8.77
153  2.00    1       0   Sun     0       24.55
211  5.16    1       1   Sat     0       25.89
198  2.00    0       1  Thur     1       13.00

In [68]:
# performing one hot encoding for day column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [69]:
ct = ColumnTransformer(transformers=[('onehot', OneHotEncoder(drop='first'),[3])], remainder='passthrough') # [3] defines the 3rd column in dataset

In [70]:
import sys 
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
X_train = ct.fit_transform(X_train)

In [71]:
X_train

array([[ 0.  ,  1.  ,  0.  ,  3.5 ,  0.  ,  0.  ,  0.  , 17.31],
       [ 0.  ,  1.  ,  0.  ,  5.65,  1.  ,  1.  ,  0.  , 23.33],
       [ 0.  ,  0.  ,  0.  ,  2.5 ,  0.  ,  1.  ,  1.  , 16.27],
       [ 1.  ,  0.  ,  0.  ,  2.01,  1.  ,  0.  ,  0.  , 20.23],
       [ 1.  ,  0.  ,  0.  ,  4.08,  0.  ,  0.  ,  0.  , 20.92],
       [ 1.  ,  0.  ,  0.  ,  2.09,  1.  ,  1.  ,  0.  , 15.01],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  7.25],
       [ 1.  ,  0.  ,  0.  ,  3.41,  1.  ,  1.  ,  0.  , 26.59],
       [ 0.  ,  1.  ,  0.  ,  3.48,  1.  ,  0.  ,  0.  , 24.52],
       [ 0.  ,  1.  ,  0.  ,  2.  ,  1.  ,  0.  ,  0.  , 19.77],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  1.  ,  1.  ,  0.  , 28.15],
       [ 0.  ,  0.  ,  1.  ,  2.71,  1.  ,  0.  ,  1.  , 17.29],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  0.  ,  0.  ,  0.  , 19.65],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  1.  ,  1.  ,  0.  , 15.53],
       [ 1.  ,  0.  ,  0.  ,  3.  ,  1.  ,  0.  ,  0.  , 20.45],
       [ 0.  ,  1.  ,  0.

In [72]:
X_test = ct.transform(X_test)

In [78]:
from sklearn.naive_bayes import BernoulliNB

In [83]:
bnb = BernoulliNB()

In [84]:
bnb.fit(X_train,y_train)

BernoulliNB()

In [85]:
y_pred = gnb.predict(X_test)

In [87]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.5573770491803278
[[ 0  2  0  0  0  0]
 [ 0 31  0  7  0  0]
 [ 0  8  0  2  0  0]
 [ 0  5  0  3  0  0]
 [ 0  2  0  0  0  0]
 [ 0  0  0  1  0  0]]
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         2
           2       0.65      0.82      0.72        38
           3       0.00      0.00      0.00        10
           4       0.23      0.38      0.29         8
           5       0.00      0.00      0.00         2
           6       0.00      0.00      0.00         1

    accuracy                           0.56        61
   macro avg       0.15      0.20      0.17        61
weighted avg       0.43      0.56      0.49        61



c:\Users\abman\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\abman\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\abman\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
