In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
from sklearn.datasets import make_classification

In [4]:
## creating classification dataset

X,y = make_classification(n_samples=1000, n_features=10, n_classes=2,random_state=35)

In [6]:
X

array([[-0.34665749,  1.57589591, -0.0607901 , ..., -0.49999483,
         1.26857676, -0.84146543],
       [ 1.0939302 , -0.08465037,  2.11438086, ..., -0.91268196,
         0.53252844, -1.05333454],
       [-0.42666753,  0.04228433,  0.97483753, ..., -0.81639596,
         0.08093646, -0.37388815],
       ...,
       [ 1.03535824,  1.26625171,  0.90000733, ...,  0.5786839 ,
         0.14763225, -0.39469223],
       [ 0.32558744, -0.58966735,  0.81832552, ...,  0.19805787,
         0.52237597, -0.62241689],
       [-0.39959962,  0.40659971, -1.42061607, ..., -0.52264523,
        -0.77217782,  0.98907892]])

In [10]:

X = pd.DataFrame(X)

In [12]:
X.head()

0         1         2         3         4         5         6  \
0 -0.346657  1.575896 -0.060790  4.295996 -0.321208 -0.670403 -1.860551   
1  1.093930 -0.084650  2.114381 -0.133080 -0.674913 -1.005651 -0.529870   
2 -0.426668  0.042284  0.974838 -0.611586 -0.261884 -0.878522  0.469229   
3 -0.838624  1.902096  0.083062 -0.345404  0.702418  0.634648  0.242955   
4  1.106399  1.006899 -1.063085  2.520071  0.839938 -0.631600 -0.599288   

          7         8         9  
0 -0.499995  1.268577 -0.841465  
1 -0.912682  0.532528 -1.053335  
2 -0.816396  0.080936 -0.373888  
3 -1.267043 -0.080835  0.027711  
4  1.092721  0.466048  0.031361

In [13]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       1000 non-null   float64
 1   1       1000 non-null   float64
 2   2       1000 non-null   float64
 3   3       1000 non-null   float64
 4   4       1000 non-null   float64
 5   5       1000 non-null   float64
 6   6       1000 non-null   float64
 7   7       1000 non-null   float64
 8   8       1000 non-null   float64
 9   9       1000 non-null   float64
dtypes: float64(10)
memory usage: 78.2 KB


In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y, test_size=0.30, random_state= 35)

In [15]:
from sklearn.linear_model import LogisticRegression

logistic = LogisticRegression()

model = logistic.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [16]:
y_pred

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0])

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

score =accuracy_score(y_test,y_pred)
print(score)
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.84
[[123  26]
 [ 22 129]]
              precision    recall  f1-score   support

           0       0.85      0.83      0.84       149
           1       0.83      0.85      0.84       151

    accuracy                           0.84       300
   macro avg       0.84      0.84      0.84       300
weighted avg       0.84      0.84      0.84       300



## Hyper Parametric Tuning

In [56]:
model= LogisticRegression()

# changing parameters of logistic regression to find the best parameter
penalty = ['l1','l2','elasticnet']
c_values = [100,10,1.0,0.01]
solver= ['saga', 'sag', 'lbfgs', 'newton-cg', 'liblinear']

In [44]:
param = dict(penalty=penalty,C=c_values,solver=solver)

In [45]:
# Grid search CV

from sklearn.model_selection import GridSearchCV, StratifiedGroupKFold
cv = StratifiedGroupKFold()
grid = GridSearchCV(estimator=model,param_grid=param,cv=cv,scoring='accuracy',n_jobs=-1)

In [46]:
grid

GridSearchCV(cv=StratifiedGroupKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['saga', 'sag', 'lbfgs', 'newton-cg',
                                    'liblinear']},
             scoring='accuracy')

In [47]:
grid.fit(X_train,y_train)

c:\Users\abman\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
160 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
20 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\abman\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\abman\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\Users\abman\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py", line 54, in _check_solver
    raise ValueError(
Val

GridSearchCV(cv=StratifiedGroupKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['saga', 'sag', 'lbfgs', 'newton-cg',
                                    'liblinear']},
             scoring='accuracy')

In [48]:
grid.best_params_

{'C': 100, 'penalty': 'l1', 'solver': 'saga'}

In [49]:
grid.best_score_

nan

In [50]:
grid.best_estimator_

LogisticRegression(C=100, penalty='l1', solver='saga')

In [54]:
y_pred1 = grid.predict(X_test)

score =accuracy_score(y_test,y_pred1)
print(score)
cm = confusion_matrix(y_test,y_pred1)
print(cm)
print(classification_report(y_test,y_pred1))

0.8433333333333334
[[123  26]
 [ 21 130]]
              precision    recall  f1-score   support

           0       0.85      0.83      0.84       149
           1       0.83      0.86      0.85       151

    accuracy                           0.84       300
   macro avg       0.84      0.84      0.84       300
weighted avg       0.84      0.84      0.84       300



## Randomized Search CV

In [55]:
from sklearn.model_selection import RandomizedSearchCV

In [58]:
randomcv = RandomizedSearchCV(estimator=model,param_distributions=param,cv=5,scoring='accuracy')

In [59]:
randomcv.fit(X_train,y_train)

c:\Users\abman\anaconda3\lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\abman\anaconda3\lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\abman\anaconda3\lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\abman\anaconda3\lib\site-packages\sklearn\svm\_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\abman\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='r

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['saga', 'sag', 'lbfgs',
                                                   'newton-cg', 'liblinear']},
                   scoring='accuracy')

In [60]:
randomcv

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['saga', 'sag', 'lbfgs',
                                                   'newton-cg', 'liblinear']},
                   scoring='accuracy')

In [61]:
randomcv.best_score_

0.8528571428571429

In [62]:
randomcv.best_params_

{'solver': 'saga', 'penalty': 'l2', 'C': 100}

In [63]:
y_pred =randomcv.predict(X_test)
score =accuracy_score(y_test,y_pred1)
print(score)
cm = confusion_matrix(y_test,y_pred1)
print(cm)
print(classification_report(y_test,y_pred1))

0.8433333333333334
[[123  26]
 [ 21 130]]
              precision    recall  f1-score   support

           0       0.85      0.83      0.84       149
           1       0.83      0.86      0.85       151

    accuracy                           0.84       300
   macro avg       0.84      0.84      0.84       300
weighted avg       0.84      0.84      0.84       300



In [64]:
X,y = make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3,random_state=42)

In [66]:
X

array([[ 0.7715326 , -1.47433614,  2.19664605, ...,  0.68174341,
         1.08996189,  0.96250289],
       [ 1.85838284, -3.68087983,  0.22749588, ..., -0.47417818,
         1.34113888, -0.77177196],
       [-0.98724764,  1.53916836,  0.5859042 , ..., -0.32202815,
        -1.45103394,  1.32543211],
       ...,
       [-1.227082  ,  1.65602784,  0.47263035, ..., -0.8634936 ,
        -1.83932326, -0.03120349],
       [ 1.28527572, -0.29715202, -0.67172079, ..., -1.31544131,
         2.85446468,  1.3094441 ],
       [-0.75428048,  0.88516075, -1.6728939 , ..., -2.0362205 ,
        -1.43989584,  0.04749347]])

In [67]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.30,random_state=42)

In [69]:
from sklearn.linear_model import LogisticRegression

# since no of classes is more than 2 we are setting up the model into ovr
logistic = LogisticRegression(multi_class='ovr')

In [73]:
model = logistic.fit(X_train,y_train)

y_pred = model.predict(X_test)

In [74]:
y_pred

array([2, 0, 1, 2, 0, 1, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 0, 0, 0,
       2, 0, 1, 0, 2, 1, 0, 2, 2, 0, 1, 0, 0, 2, 2, 2, 1, 0, 0, 1, 2, 0,
       1, 2, 1, 0, 1, 1, 2, 0, 1, 0, 2, 2, 2, 2, 1, 2, 0, 2, 2, 2, 1, 1,
       0, 1, 0, 1, 0, 2, 2, 0, 0, 0, 2, 1, 1, 2, 2, 0, 2, 1, 0, 1, 1, 2,
       1, 1, 2, 2, 1, 2, 2, 2, 1, 0, 0, 0, 0, 2, 1, 0, 2, 1, 1, 0, 0, 2,
       0, 1, 2, 0, 0, 0, 1, 1, 2, 2, 1, 0, 0, 1, 2, 0, 0, 1, 0, 2, 1, 0,
       2, 2, 2, 0, 0, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2, 0, 0, 1, 2, 0, 0, 2,
       1, 0, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 0, 0, 2,
       0, 1, 1, 2, 2, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 2, 1, 2, 2, 1, 2,
       0, 1, 2, 2, 1, 1, 0, 2, 1, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 2, 2, 2, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 1, 0, 1, 2, 0, 0, 2,
       0, 2, 0, 0, 2, 2, 0, 2, 2, 0, 1, 2, 2, 0, 1, 1, 0, 1, 2, 0, 2, 2,
       0, 0, 0, 2, 1, 2, 0, 2, 2, 2, 0, 2, 0, 2, 2, 0, 0, 1, 0, 2, 2, 2,
       0, 2, 2, 0, 2, 2, 0, 2, 0, 0, 2, 2, 0, 1])

In [76]:
score =accuracy_score(y_test,y_pred)
print(score)
cm = confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.68
[[79 16  8]
 [31 38 27]
 [ 3 11 87]]
              precision    recall  f1-score   support

           0       0.70      0.77      0.73       103
           1       0.58      0.40      0.47        96
           2       0.71      0.86      0.78       101

    accuracy                           0.68       300
   macro avg       0.67      0.67      0.66       300
weighted avg       0.67      0.68      0.66       300



## ROC curve

In [92]:
X,y =  make_classification(n_samples=1000,n_classes=2,random_state=32)

In [93]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=34)


In [94]:
#Creating a dummy model that gives 0 as output
dummy_model_prob = [0 for _ in range(len(y_test))]

In [95]:
dummy_model_prob

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0]

In [96]:
model = LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [97]:
model_prob = model.predict_proba(X_test)

In [98]:
model_prob

array([[6.36113419e-04, 9.99363887e-01],
       [8.92109783e-02, 9.10789022e-01],
       [4.52087244e-03, 9.95479128e-01],
       [9.10563016e-01, 8.94369840e-02],
       [9.44213664e-01, 5.57863360e-02],
       [6.22844009e-03, 9.93771560e-01],
       [3.88665006e-02, 9.61133499e-01],
       [9.99721375e-01, 2.78624708e-04],
       [3.38648843e-04, 9.99661351e-01],
       [9.99548525e-01, 4.51474723e-04],
       [9.96944538e-01, 3.05546213e-03],
       [9.98344738e-01, 1.65526194e-03],
       [2.47813900e-02, 9.75218610e-01],
       [9.98423545e-01, 1.57645476e-03],
       [1.96760156e-03, 9.98032398e-01],
       [9.96829888e-01, 3.17011192e-03],
       [4.67194045e-03, 9.95328060e-01],
       [9.90765248e-01, 9.23475175e-03],
       [5.92827715e-03, 9.94071723e-01],
       [2.21273215e-02, 9.77872678e-01],
       [9.92882689e-01, 7.11731102e-03],
       [8.58281442e-01, 1.41718558e-01],
       [3.84166866e-02, 9.61583313e-01],
       [7.43687597e-03, 9.92563124e-01],
       [9.958200

In [100]:
model_prob = model_prob[:,1]

In [101]:
from sklearn.metrics import roc_curve,roc_auc_score
dummy_model_auc = roc_auc_score(y_test,dummy_model_prob)
model_auc = roc_auc_score(y_test,model_prob)
print(dummy_model_auc)
print(model_auc)

0.5
0.999935064935065
